// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.wearable.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class Asset extends Message {

  public static final String DEFAULT_DIGEST = "";

  /**
   * TODO
   */
  @ProtoField(tag = 4, type = STRING)
  public final String digest;

  public Asset(String digest) {
    this.digest = digest;
  }

  private Asset(Builder builder) {
    this(builder.digest);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Asset)) return false;
    return equals(digest, ((Asset) other).digest);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = digest != null ? digest.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<Asset> {

    public String digest;

    public Builder() {
    }

    public Builder(Asset message) {
      super(message);
      if (message == null) return;
      this.digest = message.digest;
    }

    /**
     * TODO
     */
    public Builder digest(String digest) {
      this.digest = digest;
      return this;
    }

    @Override
    public Asset build() {
      return new Asset(this);
    }
  }
}
